PythonProject/PythonProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.views.static import serve #需要导入
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),#这部分很重要
    url(r'^UserInfo/', include('apps.UserInfo.urls', namespace='UserInfo')),  # 用户模块
    url(r'^Teacher/', include('apps.Teacher.urls', namespace='Teacher')),  # 老师模块
    url(r'^ResourceType/', include('apps.ResourceType.urls', namespace='ResourceType')),  # 资源类型模块
    url(r'^Resource/', include('apps.Resource.urls', namespace='Resource')),  # 教学资源模块
    url(r'^ResourceComment/', include('apps.ResourceComment.urls', namespace='ResourceComment')),  # 资源评论模块
    url(r'^Collection/', include('apps.Collection.urls', namespace='Collection')),  # 资源收藏模块
    url(r'^TeacheFollow/', include('apps.TeacheFollow.urls', namespace='TeacheFollow')),  # 老师订阅模块
    url(r'^Leaveword/', include('apps.Leaveword.urls', namespace='Leaveword')),  # 留言模块
    url(r'^Notice/', include('apps.Notice.urls', namespace='Notice')),  # 新闻公告模块

    url(r'^', include("apps.Index.urls", namespace="Index")),  # 首页模块

    url(r'^tinymce/', include('tinymce.urls')),
]

PythonProject/apps/Index/urls.py
from django.conf.urls import url
from apps.Index.views import IndexView,FrontLoginView,FrontLoginOutView,LoginView,LoginOutView,MainView,MainTeacherView,ChangePasswordView

# 正在部署的应用的名称
app_name = 'Index'

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),  # 首页
    url(r'^frontLogin$', FrontLoginView.as_view(), name='frontLogin'),  # 前台登录
    url(r'^frontLoginout$', FrontLoginOutView.as_view(), name='frontLoginout'),  # 前台退出
    url(r'^login$', LoginView.as_view(), name="login"),  # 后台登录
    url(r'^loginout$', LoginOutView.as_view(), name="loginout"),  # 后台退出
    url(r'^main$', MainView.as_view(), name='main'),  # 后台主页面
    url(r'^main_teacher$', MainTeacherView.as_view(), name='mainTeacher'),  # 后台主页面
    url(r'^changePassword$', ChangePasswordView.as_view(), name='changePassword')  # 管理员修改密码
]

PythonProject/apps/Teacher/urls.py
from apps.Teacher.views import FrontAddView, FrontListView, UpdateView, DeletesView, FrontShowView, AddView, \
    ListView, OutToExcelView, BackModifyView, BackSelfModifyView,FrontModifyView, ListAllView
from django.conf.urls import url

# 正在部署的应用的名称
app_name = 'Teacher'

urlpatterns = [
    url(r'^frontAdd$', FrontAddView.as_view(), name='frontAdd'),  # 前台添加
    url(r'^frontModify/(?P<teacherNo>.+)$', FrontModifyView.as_view(), name='frontModify'),  # 前台更新
    url(r'^frontList$', FrontListView.as_view(), name='frontList'),  # 前台查询列表
    url(r'^frontShow/(?P<teacherNo>.+)$', FrontShowView.as_view(), name='frontShow'),  # 前台显示详情页
    url(r'^listAll', ListAllView.as_view(), name='listAll'),  # 前台查询所有信息

    url(r'^update/(?P<teacherNo>.+)$', UpdateView.as_view(), name='update'),  # Ajax方式更新记录

    url(r'^add$', AddView.as_view(), name='add'),  # 后台添加
    url(r'^backModify/(?P<teacherNo>.+)$', BackModifyView.as_view(), name="backModify"),  # 后台更新
    url(r'^backSelfModify$', BackSelfModifyView.as_view(), name="backSelfModify"),  # 后台更新
    url(r'^list$', ListView.as_view(), name='list'),  # 后台信息列表
    url(r'^deletes$', DeletesView.as_view(), name="deletes"),  # 删除记录信息
    url(r'^OutToExcel$', OutToExcelView.as_view(), name='OutToExcel')  # 导出信息到excel并下载
]

PythonProject/apps/Teacher/models.py
from django.db import models
from tinymce.models import HTMLField


class Teacher(models.Model):
    teacherNo = models.CharField(max_length=30, default='', primary_key=True, verbose_name='教师编号')
    password = models.CharField(max_length=30, default='', verbose_name='登录密码')
    name = models.CharField(max_length=20, default='', verbose_name='姓名')
    sex = models.CharField(max_length=4, default='', verbose_name='性别')
    birthDate = models.CharField(max_length=20, default='', verbose_name='出生日期')
    teacherPhoto = models.ImageField(upload_to='img', max_length='100', verbose_name='老师照片')
    zhicheng = models.CharField(max_length=20, default='', verbose_name='职称')
    telephone = models.CharField(max_length=20, default='', verbose_name='联系电话')
    comeDate = models.CharField(max_length=20, default='', verbose_name='入职日期')
    address = models.CharField(max_length=80, default='', verbose_name='家庭地址')
    teacherDesc = HTMLField(max_length=5000, verbose_name='老师介绍')

    class Meta:
        db_table = 't_Teacher'
        verbose_name = '老师信息'
        verbose_name_plural = verbose_name

    def getJsonObj(self):
        teacher = {
            'teacherNo': self.teacherNo,
            'password': self.password,
            'name': self.name,
            'sex': self.sex,
            'birthDate': self.birthDate,
            'teacherPhoto': self.teacherPhoto.url,
            'zhicheng': self.zhicheng,
            'telephone': self.telephone,
            'comeDate': self.comeDate,
            'address': self.address,
            'teacherDesc': self.teacherDesc,
        }
        return teacher


PythonProject/apps/Teacher/views.py
from django.views.generic import View
from apps.BaseView import BaseView
from django.shortcuts import render
from django.core.paginator import Paginator
from apps.Teacher.models import Teacher
from django.http import JsonResponse
from django.http import FileResponse
from apps.BaseView import ImageFormatException
from django.conf import settings
import pandas as pd
import os


class FrontAddView(BaseView):  # 前台老师添加
    def primaryKeyExist(self, teacherNo):  # 判断主键是否存在
        try:
            Teacher.objects.get(teacherNo=teacherNo)
            return True
        except Teacher.DoesNotExist:
            return False

    def get(self,request):

        # 使用模板
        return render(request, 'Teacher/teacher_frontAdd.html')

    def post(self, request):
        teacherNo = request.POST.get('teacher.teacherNo') # 判断教师编号是否存在
        if self.primaryKeyExist(teacherNo):
            return JsonResponse({'success': False, 'message': '教师编号已经存在'})

        teacher = Teacher() # 新建一个老师对象然后获取参数
        teacher.teacherNo = teacherNo
        teacher.password = request.POST.get('teacher.password')
        teacher.name = request.POST.get('teacher.name')
        teacher.sex = request.POST.get('teacher.sex')
        teacher.birthDate = request.POST.get('teacher.birthDate')
        try:
            teacher.teacherPhoto = self.uploadImageFile(request,'teacher.teacherPhoto')
        except ImageFormatException as ife:
            return JsonResponse({'success': False, 'message': ife.error})
        teacher.zhicheng = request.POST.get('teacher.zhicheng')
        teacher.telephone = request.POST.get('teacher.telephone')
        teacher.comeDate = request.POST.get('teacher.comeDate')
        teacher.address = request.POST.get('teacher.address')
        teacher.teacherDesc = request.POST.get('teacher.teacherDesc')
        teacher.save() # 保存老师信息到数据库
        return JsonResponse({'success': True, 'message': '保存成功'})


class FrontModifyView(BaseView):  # 前台修改老师
    def get(self, request, teacherNo):
        context = {'teacherNo': teacherNo}
        return render(request, 'Teacher/teacher_frontModify.html', context)


class FrontListView(BaseView):  # 前台老师查询列表
    def get(self, request):
        return self.handle(request)

    def post(self, request):
        return self.handle(request)

    def handle(self, request):
        self.getCurrentPage(request)  # 获取当前要显示第几页
        # 下面获取查询参数
        teacherNo = self.getStrParam(request, 'teacherNo')
        name = self.getStrParam(request, 'name')
        birthDate = self.getStrParam(request, 'birthDate')
        zhicheng = self.getStrParam(request, 'zhicheng')
        telephone = self.getStrParam(request, 'telephone')
        # 然后条件组合查询过滤
        teachers = Teacher.objects.all()
        if teacherNo != '':
            teachers = teachers.filter(teacherNo__contains=teacherNo)
        if name != '':
            teachers = teachers.filter(name__contains=name)
        if birthDate != '':
            teachers = teachers.filter(birthDate__contains=birthDate)
        if zhicheng != '':
            teachers = teachers.filter(zhicheng__contains=zhicheng)
        if telephone != '':
            teachers = teachers.filter(telephone__contains=telephone)
        # 对查询结果利用Paginator进行分页
        self.paginator = Paginator(teachers, self.pageSize)
        # 计算总的页码数，要显示的页码列表，总记录等
        self.calculatePages()
        # 获取第page页的Page实例对象
        teachers_page = self.paginator.page(self.currentPage)

        # 构造模板需要的参数
        context = {
            'teachers_page': teachers_page,
            'teacherNo': teacherNo,
            'name': name,
            'birthDate': birthDate,
            'zhicheng': zhicheng,
            'telephone': telephone,
            'currentPage': self.currentPage,
            'totalPage': self.totalPage,
            'recordNumber': self.recordNumber,
            'startIndex': self.startIndex,
            'pageList': self.pageList,
        }
        # 渲染模板界面
        return render(request, 'Teacher/teacher_frontquery_result.html', context)


class FrontShowView(View):  # 前台显示老师详情页
    def get(self, request, teacherNo):
        # 查询需要显示的老师对象
        teacher = Teacher.objects.get(teacherNo=teacherNo)
        context = {
            'teacher': teacher
        }
        # 渲染模板显示
        return render(request, 'Teacher/teacher_frontshow.html', context)


class ListAllView(View): # 前台查询所有老师
    def get(self,request):
        teachers = Teacher.objects.all()
        teacherList = []
        for teacher in teachers:
            teacherObj = {
                'teacherNo': teacher.teacherNo,
                'name': teacher.name,
            }
            teacherList.append(teacherObj)
        return JsonResponse(teacherList, safe=False)


class UpdateView(BaseView):  # Ajax方式老师更新
    def get(self, request, teacherNo):
        # GET方式请求查询老师对象并返回老师json格式
        teacher = Teacher.objects.get(teacherNo=teacherNo)
        return JsonResponse(teacher.getJsonObj())

    def post(self, request, teacherNo):
        # POST方式提交老师修改信息更新到数据库
        teacher = Teacher.objects.get(teacherNo=teacherNo)
        teacher.password = request.POST.get('teacher.password')
        teacher.name = request.POST.get('teacher.name')
        teacher.sex = request.POST.get('teacher.sex')
        teacher.birthDate = request.POST.get('teacher.birthDate')
        try:
            teacherPhotoName = self.uploadImageFile(request, 'teacher.teacherPhoto')
        except ImageFormatException as ife:
            return JsonResponse({'success': False, 'message': ife.error})
        if teacherPhotoName != 'img/NoImage.jpg':
            teacher.teacherPhoto = teacherPhotoName
        teacher.zhicheng = request.POST.get('teacher.zhicheng')
        teacher.telephone = request.POST.get('teacher.telephone')
        teacher.comeDate = request.POST.get('teacher.comeDate')
        teacher.address = request.POST.get('teacher.address')
        teacher.teacherDesc = request.POST.get('teacher.teacherDesc')
        teacher.save()
        return JsonResponse({'success': True, 'message': '保存成功'})

class AddView(BaseView):  # 后台老师添加
    def primaryKeyExist(self, teacherNo):  # 判断主键是否存在
        try:
            Teacher.objects.get(teacherNo=teacherNo)
            return True
        except Teacher.DoesNotExist:
            return False

    def get(self,request):

        # 渲染显示模板界面
        return render(request, 'Teacher/teacher_add.html')

    def post(self, request):
        # POST方式处理图书添加业务
        teacherNo = request.POST.get('teacher.teacherNo') # 判断教师编号是否存在
        if self.primaryKeyExist(teacherNo):
            return JsonResponse({'success': False, 'message': '教师编号已经存在'})

        teacher = Teacher() # 新建一个老师对象然后获取参数
        teacher.teacherNo = teacherNo
        teacher.password = request.POST.get('teacher.password')
        teacher.name = request.POST.get('teacher.name')
        teacher.sex = request.POST.get('teacher.sex')
        teacher.birthDate = request.POST.get('teacher.birthDate')
        try:
            teacher.teacherPhoto = self.uploadImageFile(request,'teacher.teacherPhoto')
        except ImageFormatException as ife:
            return JsonResponse({'success': False, 'message': ife.error})
        teacher.zhicheng = request.POST.get('teacher.zhicheng')
        teacher.telephone = request.POST.get('teacher.telephone')
        teacher.comeDate = request.POST.get('teacher.comeDate')
        teacher.address = request.POST.get('teacher.address')
        teacher.teacherDesc = request.POST.get('teacher.teacherDesc')
        teacher.save() # 保存老师信息到数据库
        return JsonResponse({'success': True, 'message': '保存成功'})


class BackModifyView(BaseView):  # 后台更新老师
    def get(self, request, teacherNo):
        context = {'teacherNo': teacherNo}
        return render(request, 'Teacher/teacher_modify.html', context)

class BackSelfModifyView(BaseView):  # 后台更新老师
    def get(self, request):
        context = {'teacherNo': request.session.get('teacherNo')}
        return render(request, 'Teacher/teacher_modify.html', context)


class ListView(BaseView):  # 后台老师列表
    def get(self, request):
        # 使用模板
        return render(request, 'Teacher/teacher_query_result.html')

    def post(self, request):
        # 获取当前要显示第几页和每页几条数据
        self.getPageAndSize(request)
        # 收集查询参数
        teacherNo = self.getStrParam(request, 'teacherNo')
        name = self.getStrParam(request, 'name')
        birthDate = self.getStrParam(request, 'birthDate')
        zhicheng = self.getStrParam(request, 'zhicheng')
        telephone = self.getStrParam(request, 'telephone')
        # 然后条件组合查询过滤
        teachers = Teacher.objects.all()
        if teacherNo != '':
            teachers = teachers.filter(teacherNo__contains=teacherNo)
        if name != '':
            teachers = teachers.filter(name__contains=name)
        if birthDate != '':
            teachers = teachers.filter(birthDate__contains=birthDate)
        if zhicheng != '':
            teachers = teachers.filter(zhicheng__contains=zhicheng)
        if telephone != '':
            teachers = teachers.filter(telephone__contains=telephone)
        # 利用Paginator对查询结果集分页
        self.paginator = Paginator(teachers, self.pageSize)
        # 计算总的页码数，要显示的页码列表，总记录等
        self.calculatePages()
        # 获取第page页的Page实例对象
        teachers_page = self.paginator.page(self.currentPage)
        # 查询的结果集转换为列表
        teacherList = []
        for teacher in teachers_page:
            teacher = teacher.getJsonObj()
            teacherList.append(teacher)
        # 构造模板页面需要的参数
        teacher_res = {
            'rows': teacherList,
            'total': self.recordNumber,
        }
        # 渲染模板页面显示

PythonProject/templates/Teacher/teacher_frontAdd.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
<title>老师添加</title>
<link href="{% static 'plugins/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-dashen.css' %}" rel="stylesheet">
<link href="{% static 'plugins/font-awesome.css' %}" rel="stylesheet">
<link href="{% static 'plugins/animate.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-datetimepicker.min.css' %}" rel="stylesheet" media="screen">
</head>
<body style="margin-top:70px;">
<div class="container">
{% include 'header.html' %}
	<div class="col-md-12 wow fadeInLeft">
		<ul class="breadcrumb">
  			<li><a href="{% url 'Index:index' %}">首页</a></li>
  			<li><a href="{% url 'Teacher:frontList' %}">老师管理</a></li>
  			<li class="active">添加老师</li>
		</ul>
		<div class="row">
			<div class="col-md-10">
		      	<form class="form-horizontal" name="teacherAddForm" id="teacherAddForm" enctype="multipart/form-data" method="post"  class="mar_t15">
				    {% csrf_token %}
				  <div class="form-group">
					 <label for="teacher_teacherNo" class="col-md-2 text-right">教师编号:</label>
					 <div class="col-md-8"> 
					 	<input type="text" id="teacher_teacherNo" name="teacher.teacherNo" class="form-control" placeholder="请输入教师编号">
					 </div>
				  </div> 
				  <div class="form-group">
				  	 <label for="teacher_password" class="col-md-2 text-right">登录密码:</label>
				  	 <div class="col-md-8">
					    <input type="text" id="teacher_password" name="teacher.password" class="form-control" placeholder="请输入登录密码">
					 </div>
				  </div>
				  <div class="form-group">
				  	 <label for="teacher_name" class="col-md-2 text-right">姓名:</label>
				  	 <div class="col-md-8">
					    <input type="text" id="teacher_name" name="teacher.name" class="form-control" placeholder="请输入姓名">
					 </div>
				  </div>
				  <div class="form-group">
				  	 <label for="teacher_sex" class="col-md-2 text-right">性别:</label>
				  	 <div class="col-md-8">
					    <input type="text" id="teacher_sex" name="teacher.sex" class="form-control" placeholder="请输入性别">
					 </div>
				  </div>
				  <div class="form-group">
				  	 <label for="teacher_birthDateDiv" class="col-md-2 text-right">出生日期:</label>
				  	 <div class="col-md-8">
		                <div id="teacher_birthDateDiv" class="input-group date teacher_birthDate col-md-12" data-link-field="teacher_birthDate" data-link-format="yyyy-mm-dd">
		                    <input class="form-control" id="teacher_birthDate" name="teacher.birthDate" size="16" type="text" value="" placeholder="请选择出生日期" readonly>
		                    <span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>
		                    <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
		                </div>
				  	 </div>
				  </div>
				  <div class="form-group">
				  	 <label for="teacher_teacherPhoto" class="col-md-2 text-right">老师照片:</label>
				  	 <div class="col-md-8">
					    <img  class="img-responsive" id="teacher_teacherPhotoImg" border="0px"/><br/>
							    <input id="teacher_teacherPhoto" name="teacher.teacherPhoto" type="file" size="50" />
				  	 </div>
				  </div>
				  <div class="form-group">
				  	 <label for="teacher_zhicheng" class="col-md-2 text-right">职称:</label>
				  	 <div class="col-md-8">
					    <input type="text" id="teacher_zhicheng" name="teacher.zhicheng" class="form-control" placeholder="请输入职称">
					 </div>
				  </div>
				  <div class="form-group">
				  	 <label for="teacher_telephone" class="col-md-2 text-right">联系电话:</label>
				  	 <div class="col-md-8">
					    <input type="text" id="teacher_telephone" name="teacher.telephone" class="form-control" placeholder="请输入联系电话">
					 </div>
				  </div>
				  <div class="form-group">
				  	 <label for="teacher_comeDateDiv" class="col-md-2 text-right">入职日期:</label>
				  	 <div class="col-md-8">
		                <div id="teacher_comeDateDiv" class="input-group date teacher_comeDate col-md-12" data-link-field="teacher_comeDate" data-link-format="yyyy-mm-dd">
		                    <input class="form-control" id="teacher_comeDate" name="teacher.comeDate" size="16" type="text" value="" placeholder="请选择入职日期" readonly>
		                    <span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>
		                    <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
		                </div>
				  	 </div>
				  </div>
				  <div class="form-group">
				  	 <label for="teacher_address" class="col-md-2 text-right">家庭地址:</label>
				  	 <div class="col-md-8">
					    <input type="text" id="teacher_address" name="teacher.address" class="form-control" placeholder="请输入家庭地址">
					 </div>
				  </div>
				  <div class="form-group">
				  	 <label for="teacher_teacherDesc" class="col-md-2 text-right">老师介绍:</label>
				  	 <div class="col-md-8">
							    <textarea name="teacher.teacherDesc" id="teacher_teacherDesc" style="width:100%;height:300px;"></textarea>
					 </div>
				  </div>
		          <div class="form-group">
		             <span class="col-md-2"></span>
		             <span onclick="ajaxTeacherAdd();" class="btn btn-primary bottom5 top5">添加</span>
		          </div> 
		          <style>#teacherAddForm .form-group {margin:5px;}  </style>  
				</form> 
			</div>
			<div class="col-md-2"></div> 
	    </div>
	</div>
</div>
{% include 'footer.html' %}
<script src="{% static 'plugins/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap.js' %}"></script>
<script src="{% static 'plugins/wow.min.js' %}"></script>
<script src="{% static 'plugins/bootstrapvalidator/js/bootstrapValidator.min.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/bootstrap-datetimepicker.min.js' %}" charset="UTF-8"></script>
<script type="text/javascript" src="{% static 'plugins/locales/bootstrap-datetimepicker.zh-CN.js' %}" charset="UTF-8"></script>
<script src="{% static 'tiny_mce/tiny_mce.js' %}"></script>
<script>
    //实例化老师介绍编辑器
    tinyMCE.init({
        selector: "#teacher_teacherDesc",
        theme: 'advanced',
        language: "zh",
        strict_loading_mode: 1,
    });
	//提交添加老师信息
	function ajaxTeacherAdd() { 
	    $("#teacher_teacherDesc").text(tinyMCE.editors['teacher_teacherDesc'].getContent());
		//提交之前先验证表单
		$("#teacherAddForm").data('bootstrapValidator').validate();
		if(!$("#teacherAddForm").data('bootstrapValidator').isValid()){
			return;
		}
		jQuery.ajax({
			type : "post",
			url : "{% url 'Teacher:frontAdd' %}",
			dataType : "json" , 
			data: new FormData($("#teacherAddForm")[0]),
			success : function(obj) {
				if(obj.success){ 
					alert("保存成功！");
					location.reload();
				} else {
					alert(obj.message);
				}
			},
			processData: false, 
			contentType: false, 
		});
	} 
$(function(){
	/*小屏幕导航点击关闭菜单*/
    $('.navbar-collapse a').click(function(){
        $('.navbar-collapse').collapse('hide');
    });
    new WOW().init();
	//验证老师添加表单字段
	$('#teacherAddForm').bootstrapValidator({
		feedbackIcons: {
			valid: 'glyphicon glyphicon-ok',
			invalid: 'glyphicon glyphicon-remove',
			validating: 'glyphicon glyphicon-refresh'
		},
		fields: {
			"teacher.teacherNo": {
				validators: {
					notEmpty: {
						message: "教师编号不能为空",
					}
				}
			},
			"teacher.password": {
				validators: {
					notEmpty: {
						message: "登录密码不能为空",
					}
				}
			},
			"teacher.name": {
				validators: {
					notEmpty: {
						message: "姓名不能为空",
					}
				}
			},
			"teacher.sex": {
				validators: {
					notEmpty: {
						message: "性别不能为空",
					}
				}
			},
			"teacher.birthDate": {
				validators: {
					notEmpty: {
						message: "出生日期不能为空",
					}
				}
			},
			"teacher.zhicheng": {
				validators: {
					notEmpty: {
						message: "职称不能为空",
					}
				}
			},
			"teacher.telephone": {
				validators: {
					notEmpty: {
						message: "联系电话不能为空",
					}
				}
			},
			"teacher.comeDate": {
				validators: {
					notEmpty: {
						message: "入职日期不能为空",
					}
				}
			},
		}
	}); 
	//出生日期组件
	$('#teacher_birthDateDiv').datetimepicker({
		language:  'zh-CN',  //显示语言
		format: 'yyyy-mm-dd',
		minView: 2,
		weekStart: 1,
		todayBtn:  1,
		autoclose: 1,
		minuteStep: 1,
		todayHighlight: 1,
		startView: 2,
		forceParse: 0
	}).on('hide',function(e) {
		//下面这行代码解决日期组件改变日期后不验证的问题
		$('#teacherAddForm').data('bootstrapValidator').updateStatus('teacher.birthDate', 'NOT_VALIDATED',null).validateField('teacher.birthDate');
	});
	//入职日期组件
	$('#teacher_comeDateDiv').datetimepicker({
		language:  'zh-CN',  //显示语言
		format: 'yyyy-mm-dd',
		minView: 2,
		weekStart: 1,
		todayBtn:  1,
		autoclose: 1,
		minuteStep: 1,
		todayHighlight: 1,
		startView: 2,
		forceParse: 0
	}).on('hide',function(e) {
		//下面这行代码解决日期组件改变日期后不验证的问题
		$('#teacherAddForm').data('bootstrapValidator').updateStatus('teacher.comeDate', 'NOT_VALIDATED',null).validateField('teacher.comeDate');
	});
})
</script>
</body>
</html>