PythonProject/PythonProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.views.static import serve #需要导入
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),#这部分很重要
    url(r'^UserInfo/', include('apps.UserInfo.urls', namespace='UserInfo')),  # 用户模块
    url(r'^Teacher/', include('apps.Teacher.urls', namespace='Teacher')),  # 老师模块
    url(r'^ResourceType/', include('apps.ResourceType.urls', namespace='ResourceType')),  # 资源类型模块
    url(r'^Resource/', include('apps.Resource.urls', namespace='Resource')),  # 教学资源模块
    url(r'^ResourceComment/', include('apps.ResourceComment.urls', namespace='ResourceComment')),  # 资源评论模块
    url(r'^Collection/', include('apps.Collection.urls', namespace='Collection')),  # 资源收藏模块
    url(r'^TeacheFollow/', include('apps.TeacheFollow.urls', namespace='TeacheFollow')),  # 老师订阅模块
    url(r'^Leaveword/', include('apps.Leaveword.urls', namespace='Leaveword')),  # 留言模块
    url(r'^Notice/', include('apps.Notice.urls', namespace='Notice')),  # 新闻公告模块

    url(r'^', include("apps.Index.urls", namespace="Index")),  # 首页模块

    url(r'^tinymce/', include('tinymce.urls')),
]

PythonProject/apps/Collection/urls.py
from apps.Collection.views import FrontAddView, FrontUserAddView, FrontListView,FrontUserListView, UpdateView, DeletesView, FrontShowView, AddView, \
    ListView, OutToExcelView, BackModifyView, FrontModifyView, ListAllView
from django.conf.urls import url

# 正在部署的应用的名称
app_name = 'Collection'

urlpatterns = [
    url(r'^frontAdd$', FrontAddView.as_view(), name='frontAdd'),  # 前台添加
    url(r'^userFrontAdd$', FrontUserAddView.as_view(), name='userFrontAdd'),  # 前台添加
    url(r'^frontModify/(?P<collectionId>.+)$', FrontModifyView.as_view(), name='frontModify'),  # 前台更新
    url(r'^frontList$', FrontListView.as_view(), name='frontList'),  # 前台查询列表
    url(r'^userFrontList$', FrontUserListView.as_view(), name='userFrontList'),  # 前台查询列表
    url(r'^frontShow/(?P<collectionId>.+)$', FrontShowView.as_view(), name='frontShow'),  # 前台显示详情页
    url(r'^listAll', ListAllView.as_view(), name='listAll'),  # 前台查询所有信息

    url(r'^update/(?P<collectionId>.+)$', UpdateView.as_view(), name='update'),  # Ajax方式更新记录

    url(r'^add$', AddView.as_view(), name='add'),  # 后台添加
    url(r'^backModify/(?P<collectionId>.+)$', BackModifyView.as_view(), name="backModify"),  # 后台更新
    url(r'^list$', ListView.as_view(), name='list'),  # 后台信息列表
    url(r'^deletes$', DeletesView.as_view(), name="deletes"),  # 删除记录信息
    url(r'^OutToExcel$', OutToExcelView.as_view(), name='OutToExcel')  # 导出信息到excel并下载
]

PythonProject/apps/Index/urls.py
from django.conf.urls import url
from apps.Index.views import IndexView,FrontLoginView,FrontLoginOutView,LoginView,LoginOutView,MainView,MainTeacherView,ChangePasswordView

# 正在部署的应用的名称
app_name = 'Index'

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),  # 首页
    url(r'^frontLogin$', FrontLoginView.as_view(), name='frontLogin'),  # 前台登录
    url(r'^frontLoginout$', FrontLoginOutView.as_view(), name='frontLoginout'),  # 前台退出
    url(r'^login$', LoginView.as_view(), name="login"),  # 后台登录
    url(r'^loginout$', LoginOutView.as_view(), name="loginout"),  # 后台退出
    url(r'^main$', MainView.as_view(), name='main'),  # 后台主页面
    url(r'^main_teacher$', MainTeacherView.as_view(), name='mainTeacher'),  # 后台主页面
    url(r'^changePassword$', ChangePasswordView.as_view(), name='changePassword')  # 管理员修改密码
]

PythonProject/apps/Collection/models.py
from django.db import models
from apps.Resource.models import Resource
from apps.UserInfo.models import UserInfo


class Collection(models.Model):
    collectionId = models.AutoField(primary_key=True, verbose_name='收藏id')
    resourceObj = models.ForeignKey(Resource,  db_column='resourceObj', on_delete=models.PROTECT, verbose_name='收藏的资源')
    userObj = models.ForeignKey(UserInfo,  db_column='userObj', on_delete=models.PROTECT, verbose_name='收藏用户')
    collectTime = models.CharField(max_length=20, default='', verbose_name='收藏时间')

    class Meta:
        db_table = 't_Collection'
        verbose_name = '资源收藏信息'
        verbose_name_plural = verbose_name

    def getJsonObj(self):
        collection = {
            'collectionId': self.collectionId,
            'resourceObj': self.resourceObj.resourceName,
            'resourceObjPri': self.resourceObj.resourceId,
            'userObj': self.userObj.name,
            'userObjPri': self.userObj.user_name,
            'collectTime': self.collectTime,
        }
        return collection


PythonProject/apps/Collection/views.py
from django.views.generic import View
from apps.BaseView import BaseView
from django.shortcuts import render
from django.core.paginator import Paginator
from apps.Collection.models import Collection
from apps.Resource.models import Resource
from apps.UserInfo.models import UserInfo
from django.http import JsonResponse
from django.http import FileResponse
from apps.BaseView import ImageFormatException
from django.conf import settings
import pandas as pd
import os


class FrontAddView(BaseView):  # 前台资源收藏添加
    def get(self,request):
        resources = Resource.objects.all()  # 获取所有教学资源
        userInfos = UserInfo.objects.all()  # 获取所有用户
        context = {
            'resources': resources,
            'userInfos': userInfos,
        }

        # 使用模板
        return render(request, 'Collection/collection_frontAdd.html', context)

    def post(self, request):
        collection = Collection() # 新建一个资源收藏对象然后获取参数
        collection.resourceObj = Resource.objects.get(resourceId=request.POST.get('collection.resourceObj.resourceId'))
        collection.userObj = UserInfo.objects.get(user_name=request.POST.get('collection.userObj.user_name'))
        collection.collectTime = request.POST.get('collection.collectTime')
        collection.save() # 保存资源收藏信息到数据库
        return JsonResponse({'success': True, 'message': '保存成功'})


class FrontUserAddView(BaseView):  # 前台资源收藏添加
    def post(self, request):
        user_name = request.session.get('user_name')
        if user_name == None:
            return JsonResponse({'success': False, 'message': '请先登录网站'})
        collection = Collection() # 新建一个资源收藏对象然后获取参数
        collection.resourceObj = Resource.objects.get(resourceId=request.POST.get('collection.resourceObj.resourceId'))
        collection.userObj = UserInfo.objects.get(user_name=user_name)
        import datetime
        collection.collectTime = str(datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S'))
        # 判断是否已经收藏过资源
        sql = "select *  from t_collection where resourceObj=" + str(collection.resourceObj.resourceId) + " and userObj='" + user_name + "'"
        # print(sql)
        collections = Collection.objects.raw(sql)
        conflictCount = len(collections)
        print("冲突记录数:", conflictCount)
        if conflictCount > 0:
            return JsonResponse({'success': False, 'message': '你已经收藏过这个资源了！'})

        collection.save() # 保存资源收藏信息到数据库
        return JsonResponse({'success': True, 'message': '保存成功'})



class FrontModifyView(BaseView):  # 前台修改资源收藏
    def get(self, request, collectionId):
        context = {'collectionId': collectionId}
        return render(request, 'Collection/collection_frontModify.html', context)


class FrontListView(BaseView):  # 前台资源收藏查询列表
    def get(self, request):
        return self.handle(request)

    def post(self, request):
        return self.handle(request)

    def handle(self, request):
        self.getCurrentPage(request)  # 获取当前要显示第几页
        # 下面获取查询参数
        resourceObj_resourceId = self.getIntParam(request, 'resourceObj.resourceId')
        userObj_user_name = self.getStrParam(request, 'userObj.user_name')
        collectTime = self.getStrParam(request, 'collectTime')
        # 然后条件组合查询过滤
        collections = Collection.objects.all()
        if resourceObj_resourceId != '0':
            collections = collections.filter(resourceObj=resourceObj_resourceId)
        if userObj_user_name != '':
            collections = collections.filter(userObj=userObj_user_name)
        if collectTime != '':
            collections = collections.filter(collectTime__contains=collectTime)
        # 对查询结果利用Paginator进行分页
        self.paginator = Paginator(collections, self.pageSize)
        # 计算总的页码数，要显示的页码列表，总记录等
        self.calculatePages()
        # 获取第page页的Page实例对象
        collections_page = self.paginator.page(self.currentPage)

        # 获取所有教学资源
        resources = Resource.objects.all()
        # 获取所有用户
        userInfos = UserInfo.objects.all()
        # 构造模板需要的参数
        context = {
            'resources': resources,
            'userInfos': userInfos,
            'collections_page': collections_page,
            'resourceObj_resourceId': int(resourceObj_resourceId),
            'userObj_user_name': userObj_user_name,
            'collectTime': collectTime,
            'currentPage': self.currentPage,
            'totalPage': self.totalPage,
            'recordNumber': self.recordNumber,
            'startIndex': self.startIndex,
            'pageList': self.pageList,
        }
        # 渲染模板界面
        return render(request, 'Collection/collection_frontquery_result.html', context)


class FrontUserListView(BaseView):  # 前台资源收藏查询列表
    def get(self, request):
        return self.handle(request)

    def post(self, request):
        return self.handle(request)

    def handle(self, request):
        self.getCurrentPage(request)  # 获取当前要显示第几页
        # 下面获取查询参数
        resourceObj_resourceId = self.getIntParam(request, 'resourceObj.resourceId')
        userObj_user_name = request.session.get('user_name')
        collectTime = self.getStrParam(request, 'collectTime')
        # 然后条件组合查询过滤
        collections = Collection.objects.all()
        if resourceObj_resourceId != '0':
            collections = collections.filter(resourceObj=resourceObj_resourceId)
        if userObj_user_name != '':
            collections = collections.filter(userObj=userObj_user_name)
        if collectTime != '':
            collections = collections.filter(collectTime__contains=collectTime)
        # 对查询结果利用Paginator进行分页
        self.paginator = Paginator(collections, self.pageSize)
        # 计算总的页码数，要显示的页码列表，总记录等
        self.calculatePages()
        # 获取第page页的Page实例对象
        collections_page = self.paginator.page(self.currentPage)

        # 获取所有教学资源
        resources = Resource.objects.all()
        # 获取所有用户
        userInfos = UserInfo.objects.all()
        # 构造模板需要的参数
        context = {
            'resources': resources,
            'userInfos': userInfos,
            'collections_page': collections_page,
            'resourceObj_resourceId': int(resourceObj_resourceId),
            'userObj_user_name': userObj_user_name,
            'collectTime': collectTime,
            'currentPage': self.currentPage,
            'totalPage': self.totalPage,
            'recordNumber': self.recordNumber,
            'startIndex': self.startIndex,
            'pageList': self.pageList,
        }
        # 渲染模板界面
        return render(request, 'Collection/collection_userFrontquery_result.html', context)



class FrontShowView(View):  # 前台显示资源收藏详情页
    def get(self, request, collectionId):
        # 查询需要显示的资源收藏对象
        collection = Collection.objects.get(collectionId=collectionId)
        context = {
            'collection': collection
        }
        # 渲染模板显示
        return render(request, 'Collection/collection_frontshow.html', context)


class ListAllView(View): # 前台查询所有资源收藏
    def get(self,request):
        collections = Collection.objects.all()
        collectionList = []
        for collection in collections:
            collectionObj = {
                'collectionId': collection.collectionId,
            }
            collectionList.append(collectionObj)
        return JsonResponse(collectionList, safe=False)


class UpdateView(BaseView):  # Ajax方式资源收藏更新
    def get(self, request, collectionId):
        # GET方式请求查询资源收藏对象并返回资源收藏json格式
        collection = Collection.objects.get(collectionId=collectionId)
        return JsonResponse(collection.getJsonObj())

    def post(self, request, collectionId):
        # POST方式提交资源收藏修改信息更新到数据库
        collection = Collection.objects.get(collectionId=collectionId)
        collection.resourceObj = Resource.objects.get(resourceId=request.POST.get('collection.resourceObj.resourceId'))
        collection.userObj = UserInfo.objects.get(user_name=request.POST.get('collection.userObj.user_name'))
        collection.collectTime = request.POST.get('collection.collectTime')
        collection.save()
        return JsonResponse({'success': True, 'message': '保存成功'})

class AddView(BaseView):  # 后台资源收藏添加
    def get(self,request):
        resources = Resource.objects.all()  # 获取所有教学资源
        userInfos = UserInfo.objects.all()  # 获取所有用户
        context = {
            'resources': resources,
            'userInfos': userInfos,
        }

        # 渲染显示模板界面
        return render(request, 'Collection/collection_add.html', context)

    def post(self, request):
        # POST方式处理图书添加业务
        collection = Collection() # 新建一个资源收藏对象然后获取参数
        collection.resourceObj = Resource.objects.get(resourceId=request.POST.get('collection.resourceObj.resourceId'))
        collection.userObj = UserInfo.objects.get(user_name=request.POST.get('collection.userObj.user_name'))
        collection.collectTime = request.POST.get('collection.collectTime')
        collection.save() # 保存资源收藏信息到数据库
        return JsonResponse({'success': True, 'message': '保存成功'})


class BackModifyView(BaseView):  # 后台更新资源收藏
    def get(self, request, collectionId):
        context = {'collectionId': collectionId}
        return render(request, 'Collection/collection_modify.html', context)


class ListView(BaseView):  # 后台资源收藏列表
    def get(self, request):
        # 使用模板
        return render(request, 'Collection/collection_query_result.html')

    def post(self, request):
        # 获取当前要显示第几页和每页几条数据
        self.getPageAndSize(request)
        # 收集查询参数
        resourceObj_resourceId = self.getIntParam(request, 'resourceObj.resourceId')
        userObj_user_name = self.getStrParam(request, 'userObj.user_name')
        collectTime = self.getStrParam(request, 'collectTime')
        # 然后条件组合查询过滤
        collections = Collection.objects.all()

PythonProject/templates/Collection/collection_add.html
{% include 'check_logstate.html' %}
{% load staticfiles %}

 <link rel="stylesheet" type="text/css" href="{% static 'css/collection.css' %}" />
<div id="collectionAddDiv">
    {% csrf_token %}
	<form id="collectionAddForm" enctype="multipart/form-data"  method="post">
		<div>
			<span class="label">收藏的资源:</span>
			<span class="inputControl">
                <select id="collection_resourceObj_resourceId" name="collection.resourceObj.resourceId" style="width:200px;height:25px;">
                    {% for resource in resources %}
                    <option value="{{ resource.resourceId }}">{{ resource.resourceName }}</option>
                    {% endfor %}
                </select>
			</span>
		</div>
		<div>
			<span class="label">收藏用户:</span>
			<span class="inputControl">
                <select id="collection_userObj_user_name" name="collection.userObj.user_name" style="width:200px;height:25px;">
                    {% for userInfo in userInfos %}
                    <option value="{{ userInfo.user_name }}">{{ userInfo.name }}</option>
                    {% endfor %}
                </select>
			</span>
		</div>
		<div>
			<span class="label">收藏时间:</span>
			<span class="inputControl">
				<input class="textbox" type="text" id="collection_collectTime" name="collection.collectTime" />

			</span>

		</div>
		<div class="operation">
			<a id="collectionAddButton" class="easyui-linkbutton">添加</a>
			<a id="collectionClearButton" class="easyui-linkbutton">重填</a>
		</div> 
	</form>
</div>
<script src="{% static 'js/Collection/collection_add.js' %}"></script>

PythonProject/templates/Collection/collection_frontAdd.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
<title>资源收藏添加</title>
<link href="{% static 'plugins/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-dashen.css' %}" rel="stylesheet">
<link href="{% static 'plugins/font-awesome.css' %}" rel="stylesheet">
<link href="{% static 'plugins/animate.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-datetimepicker.min.css' %}" rel="stylesheet" media="screen">
</head>
<body style="margin-top:70px;">
{% include 'header.html' %}
<div class="container">
	<div class="row">
		<div class="col-md-12 wow fadeInUp" data-wow-duration="0.5s">
			<div>
				<!-- Nav tabs -->
				<ul class="nav nav-tabs" role="tablist">
			    	<li role="presentation" ><a href="{% url 'Collection:frontList' %}">资源收藏列表</a></li>
			    	<li role="presentation" class="active"><a href="#collectionAdd" aria-controls="collectionAdd" role="tab" data-toggle="tab">添加资源收藏</a></li>
				</ul>
				<!-- Tab panes -->
				<div class="tab-content">
				    <div role="tabpanel" class="tab-pane" id="collectionList">
				    </div>
				    <div role="tabpanel" class="tab-pane active" id="collectionAdd"> 
				      	<form class="form-horizontal" name="collectionAddForm" id="collectionAddForm" enctype="multipart/form-data" method="post"  class="mar_t15">
				    {% csrf_token %}
						  <div class="form-group">
						  	 <label for="collection_resourceObj_resourceId" class="col-md-2 text-right">收藏的资源:</label>
						  	 <div class="col-md-8">
							    <select id="collection_resourceObj_resourceId" name="collection.resourceObj.resourceId" class="form-control">
                            {% for resource in resources %}
                            <option value="{{ resource.resourceId }}">{{ resource.resourceName }}</option>
                            {% endfor %}
							    </select>
						  	 </div>
						  </div>
						  <div class="form-group">
						  	 <label for="collection_userObj_user_name" class="col-md-2 text-right">收藏用户:</label>
						  	 <div class="col-md-8">
							    <select id="collection_userObj_user_name" name="collection.userObj.user_name" class="form-control">
                            {% for userInfo in userInfos %}
                            <option value="{{ userInfo.user_name }}">{{ userInfo.name }}</option>
                            {% endfor %}
							    </select>
						  	 </div>
						  </div>
						  <div class="form-group">
						  	 <label for="collection_collectTimeDiv" class="col-md-2 text-right">收藏时间:</label>
						  	 <div class="col-md-8">
				                <div id="collection_collectTimeDiv" class="input-group date collection_collectTime col-md-12" data-link-field="collection_collectTime">
				                    <input class="form-control" id="collection_collectTime" name="collection.collectTime" size="16" type="text" value="" placeholder="请选择收藏时间" readonly>
				                    <span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>
				                    <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
				                </div>
						  	 </div>
						  </div>
				          <div class="form-group">
				             <span class="col-md-2"></span>
				             <span onclick="ajaxCollectionAdd();" class="btn btn-primary bottom5 top5">添加</span>
				          </div>
						</form> 
				        <style>#collectionAddForm .form-group {margin:10px;}  </style>
					</div>
				</div>
			</div>
		</div>
	</div> 
</div>

{% include 'footer.html' %}
<script src="{% static 'plugins/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap.js' %}"></script>
<script src="{% static 'plugins/wow.min.js' %}"></script>
<script src="{% static 'plugins/bootstrapvalidator/js/bootstrapValidator.min.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/bootstrap-datetimepicker.min.js' %}" charset="UTF-8"></script>
<script type="text/javascript" src="{% static 'plugins/locales/bootstrap-datetimepicker.zh-CN.js' %}" charset="UTF-8"></script>
<script>
	//提交添加资源收藏信息
	function ajaxCollectionAdd() { 
		//提交之前先验证表单
		$("#collectionAddForm").data('bootstrapValidator').validate();
		if(!$("#collectionAddForm").data('bootstrapValidator').isValid()){
			return;
		}
		jQuery.ajax({
			type : "post",
			url : "{% url 'Collection:frontAdd' %}",
			dataType : "json" , 
			data: new FormData($("#collectionAddForm")[0]),
			success : function(obj) {
				if(obj.success){ 
					alert("保存成功！");
					location.reload();
				} else {
					alert(obj.message);
				}
			},
			processData: false, 
			contentType: false, 
		});
	} 
$(function(){
	/*小屏幕导航点击关闭菜单*/
    $('.navbar-collapse a').click(function(){
        $('.navbar-collapse').collapse('hide');
    });
    new WOW().init();
	//验证资源收藏添加表单字段
	$('#collectionAddForm').bootstrapValidator({
		feedbackIcons: {
			valid: 'glyphicon glyphicon-ok',
			invalid: 'glyphicon glyphicon-remove',
			validating: 'glyphicon glyphicon-refresh'
		},
		fields: {
			"collection.collectTime": {
				validators: {
					notEmpty: {
						message: "收藏时间不能为空",
					}
				}
			},
		}
	}); 
	//收藏时间组件
	$('#collection_collectTimeDiv').datetimepicker({
		language:  'zh-CN',  //显示语言
		format: 'yyyy-mm-dd hh:ii:ss',
		weekStart: 1,
		todayBtn:  1,
		autoclose: 1,
		minuteStep: 1,
		todayHighlight: 1,
		startView: 2,
		forceParse: 0
	}).on('hide',function(e) {
		//下面这行代码解决日期组件改变日期后不验证的问题
		$('#collectionAddForm').data('bootstrapValidator').updateStatus('collection.collectTime', 'NOT_VALIDATED',null).validateField('collection.collectTime');
	});
})
</script>
</body>
</html>

PythonProject/templates/Collection/collection_frontshow.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
  <TITLE>查看资源收藏详情</TITLE>
  <link href="{% static 'plugins/bootstrap.css' %}" rel="stylesheet">
  <link href="{% static 'plugins/bootstrap-dashen.css' %}" rel="stylesheet">
  <link href="{% static 'plugins/font-awesome.css' %}" rel="stylesheet">
  <link href="{% static 'plugins/animate.css' %}" rel="stylesheet">
</head>
<body style="margin-top:70px;"> 
{% include 'header.html' %}
<div class="container">
	<ul class="breadcrumb">
  		<li><a href={% url 'Index:index' %}">首页</a></li>
  		<li><a href="{% url 'Collection:frontList' %}">资源收藏信息</a></li>
  		<li class="active">详情查看</li>
	</ul>
	<div class="row bottom15"> 
		<div class="col-md-2 col-xs-4 text-right bold">收藏id:</div>
		<div class="col-md-10 col-xs-6">{{ collection.collectionId }}</div>
	</div>
	<div class="row bottom15"> 
		<div class="col-md-2 col-xs-4 text-right bold">收藏的资源:</div>
		<div class="col-md-10 col-xs-6">{{ collection.resourceObj.resourceName }}</div>
	</div>
	<div class="row bottom15"> 
		<div class="col-md-2 col-xs-4 text-right bold">收藏用户:</div>
		<div class="col-md-10 col-xs-6">{{ collection.userObj.name }}</div>
	</div>
	<div class="row bottom15"> 
		<div class="col-md-2 col-xs-4 text-right bold">收藏时间:</div>
		<div class="col-md-10 col-xs-6">{{ collection.collectTime }}</div>
	</div>
	<div class="row bottom15">
		<div class="col-md-2 col-xs-4"></div>
		<div class="col-md-6 col-xs-6">
			<button onclick="history.back();" class="btn btn-primary">返回</button>
		</div>
	</div>
</div> 
{% include 'footer.html' %}
<script src="{% static 'plugins/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap.js' %}"></script>
<script src="{% static 'plugins/wow.min.js' %}"></script>
<script>
$(function(){
        /*小屏幕导航点击关闭菜单*/
        $('.navbar-collapse a').click(function(){
            $('.navbar-collapse').collapse('hide');
        });
        new WOW().init();
 })
 </script> 
</body>
</html>


PythonProject/templates/Collection/collection_modify.html
{% load staticfiles %}
{% include 'check_logstate.html' %}
<link rel="stylesheet" type="text/css" href="{% static 'css/collection.css' %}" />
<div id="collection_EditDiv">
	<form id="collectionModifyForm" enctype="multipart/form-data"  method="post">
        {% csrf_token %}
		<div>
			<span class="label">收藏id:</span>
			<span class="inputControl">
				<input class="textbox" type="text" id="collection_collectionId_modify" name="collection.collectionId" value="{{ collectionId }}" style="width:200px" />
			</span>
		</div>

		<div>
			<span class="label">收藏的资源:</span>
			<span class="inputControl">
				<input class="textbox"  id="collection_resourceObj_resourceId_modify" name="collection.resourceObj.resourceId" style="width: auto"/>
			</span>
		</div>
		<div>
			<span class="label">收藏用户:</span>
			<span class="inputControl">
				<input class="textbox"  id="collection_userObj_user_name_modify" name="collection.userObj.user_name" style="width: auto"/>
			</span>
		</div>
		<div>
			<span class="label">收藏时间:</span>
			<span class="inputControl">
				<input class="textbox" type="text" id="collection_collectTime_modify" name="collection.collectTime" />

			</span>

		</div>
		<div class="operation">
			<a id="collectionModifyButton" class="easyui-linkbutton">更新</a> 
		</div>
	</form>
</div>
<script src="{% static 'js/Collection/collection_modify.js' %}"></script>